forge 'https://forgeapi.puppetlabs.com'

mod 'puppet-letsencrypt', '2.0.0'
mod 'puppet-nginx', '0.6.0'
mod 'puppet-nodejs', '2.3.0'
mod 'puppetlabs-git', '0.5.0'
mod 'puppetlabs-mongodb', '0.17.0'
mod 'puppetlabs-stdlib', '4.16.0'
mod 'puppetlabs-vcsrepo', '1.5.0'
mod 'stankevich-python', '1.18.2'
